export const productsData: { name: string; price: number }[] = [
  { name: "Laptop", price: 999 },
  { name: "Wireless Mouse", price: 29 },
  { name: "Mechanical Keyboard", price: 149 },
  { name: "USB-C Hub", price: 79 },
  { name: "Monitor 27\"", price: 349 },
  { name: "Webcam HD", price: 89 },
  { name: "Headphones", price: 129 },
  { name: "SSD 1TB", price: 119 },
  { name: "Desk Lamp", price: 45 },
  { name: "Standing Desk", price: 399 },
  { name: "Ergonomic Chair", price: 299 },
  { name: "Laptop Stand", price: 59 },
  { name: "Cable Organizer", price: 19 },
  { name: "Power Strip", price: 34 },
  { name: "Smart Watch", price: 249 },
  { name: "Tablet 10\"", price: 329 },
  { name: "External SSD", price: 159 },
  { name: "Bluetooth Speaker", price: 79 },
];
